Repository uday03meh/RockPaperScissors, pull requests merged in 2022-10, with the labels that each got.

#5 Resolved the Bug
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#14 added highScore feature
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 Update the Readme file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 Saved scores into localStorage
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#21 Improved Readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#22 Added favicon and changed title
  .DS_Store
  img/.DS_Store
  img/favicon.ico
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#24 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#25 Display Player's choice
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#26 Add Reset Button
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#28 I have added sounds to the game.
  script.js
  sounds/Draw.wav
  sounds/Tada-sound.mp3
  sounds/Win.mp3
  sounds/gameover.wav
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Updated README with game play short webm video
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#30 added animations and a title
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#32 Add keyboard interaction and its instructions
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#35 Added deployed link in readme
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Rectified the Score-Rendering and Reference Error
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#38 Reference/Syntax Error (issue no. #36)
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#39 Add keyboard interaction
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#41 Rectified alignment issue and added transform feature to 'Again!' button
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#43 I tried to add sounds of smaller duration.
  script.js
  sounds/Draw2.wav
  sounds/Win3.wav
  sounds/_gameover2.wav
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added the functionality to reset score to zero after reloading
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#46 CSS Styles updated and corrected.
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#50 Added new button
  .vscode/settings.json
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#51 Fixed Consistency in Desktop Mode
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#52 Update readme
  README.md
  site demo/final_63580dce49fc0921e9547f89_194957.gif
Labels: hacktoberfest, hacktoberfest-accepted
